kind: pipeline
type: docker
name: default

concurrency:
  limit: 1

clone:
  disable: true

steps:
- name: fetch 
  pull: never
  image: zkopru/git
  commands:
    - git clone -b ${DRONE_BRANCH} https://github.com:${DRONE_REPO}.git

- name: build
  image: node:16-alpine
  commands:
    - cd ${DRONE_REPO_NAME}
    - yarn && npx gatsby build --prefix-paths

- name: publish
  pull: never
  image: stress-test/publisher
  commands:
    - cd ${DRONE_REPO_NAME}
    - npx gh-pages -d public

- name: push-main
  pull: never
  image: stress-test/publisher
  commands:
    - cd ${DRONE_REPO_NAME}
    - git checkout -b main --track origin/main
    - git merge ${DRONE_BRANCH}
    - git push origin main

trigger:
  branch:
    include:
      - result/*
  event:
    - push
